cmd: "python"
name: "Default"
args:
 - "src"
sh: true
targets:
    test-tx:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.tx"
    test-field-general:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.field.general"
    test-field-script:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.field.script"
    test-address:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.address.address"
