cmd: "python"
name: "Default"
args:
 - "src"
sh: true
targets:
    test-tx:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.tx"
    test-field-general:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.field.general"
    test-field-script:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.field.script"
    test-address:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.address.test"
    test-tx-output:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.io.output.test"
    test-tx-creation:
        cmd: "python"
        args:
          - "-m"
          - "src.tests.test-tx"
