cmd: "python"
name: "Default"
args:
 - "src"
sh: true
targets:
    test-tx:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.tx"
    test-tx-field:
        cmd: "python"
        args:
         - "-m"
         - "src.bitcoin.field.tx"
