cmd: "python"
name: "default"
args:
  - "src"
sh: true,
targets:
  test:
    cmd: "python"
    args:
      - "tests"
  test-multisig:
    cmd: "python"
    args:
      - "tests/multisig.py"
  test-base58:
    cmd: "python"
    args:
      - "tests/base58tests.py"
